apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    apps: node-app
spec:
  selector:
    app: node-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 7080
    nodePort: 31110
